# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 3
error_model depolarizing_channel, 0.01

.init
load_state toffoli_state.qst

.toffoli_gate
   tdag q0 | tdag q1 | h q2
   cnot q2,q0
   t q01 | cnot q1,q2
   cnot q1,q0 | t q2
   tdag q0 | cnot q1,q2
   cnot q2,q0
   t q0 | tdag q2
   cnot q1,q0 | h q2
   measure q0 | measure q1 | measure q2
